;=============SOJIB HASAN===============
;=============06 December 2025==========
; This is the source code (.asm file) for exercise 5 on ADuC V3/V4 board.
; The program shows a rinning light on the LED's with a variable delay.
; Thomas More University
; Written by Roggemans M. (MGM) v2 on 02-02-2015
; Revisited by MGM 07-2022.

		org	0000h			     ;starting address code

; A running light can be generated by writing consecutively 01111111b, 10111111b, 1101111b,etc
; to the LED's... 
; Use "mov" instructions to do so. Do not forget to insert delay functions.

		mov	a,p0		;load value in a register

loop:	mov	p2,#01111111b			;LED's updated
        lcall	delaya0k05s
	    mov	p2,#10111111b
        lcall	delaya0k05s
	    mov	p2,#11011111b
        lcall	delaya0k05s
        mov	p2,#11101111b
        lcall	delaya0k05s
        mov	p2,#11110111b
        lcall	delaya0k05s
        mov	p2,#11111011b
        lcall	delaya0k05s
        mov	p2,#11111101b
        lcall	delaya0k05s
        mov	p2,#11111110b
        lcall	delaya0k05s
; A delay is needed

			;repeat until all desired values are shown

; A delay is needed

;repeat

		ljmp	loop		;infinite loop

#include	"c:\aducgd1.inc"

